spring:
  application:
    name: spring-cloud-eureka-client
server:
  port: 0
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
#    healthcheck:
#      enabled: true
  instance:
    non-secure-port: 0
    preferIpAddress: true
#    healthCheckUrl: http://${eureka.hostname}/health
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}